server:
  port: 8363

eureka:
  instance:
    hostname: eureka03
  client:
    service-url:
      defaultZone: http://eureka01:8361/eureka,http://eureka02:8362/eureka,http://eureka03:8363/eureka
    register-with-eureka: false
    fetch-registry: false
