server:
  port: 8061

spring:
  application:
    name: gateway_server
  cloud:
    gateway:
      default-filters:
      routes:
      - id:  user-server
        # lb代表从注册中心获取服务
        uri: lb://consumer-user
        predicates:
        #- RemoteAddr=223.104.3.1/24
        #- Path=/getPort
        - Method=GET
        #- After=2020-03-19T15:55:06+08:00[Asia/Shanghai]
        #- Before=2020-03-19T15:56:06+08:00[Asia/Shanghai]
       # - Between=2020-03-19T15:55:06+08:00[Asia/Shanghai],2020-03-19T15:56:06+08:00[Asia/Shanghai]
        filters:
        #- AddRequestParameter=age, three
        - RewritePath=/getport, /getPort  #/foo/(?<segment>.*), /$\{segment}
        #- PrefixPath=/mypath

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://eureka01:8361/eureka,http://eureka02:8362/eureka,http://eureka03:8363/eureka
  instance:
          lease-expiration-duration-in-seconds: 6
          lease-renewal-interval-in-seconds: 3
