server:
  port: 2100

spring:
  application:
    name: product-service

eureka:
  client:
    service-url:
      defaultZone: http://eureka01:8361/eureka,http://eureka02:8362/eureka,http://eureka03:8363/eureka
  instance:
    lease-expiration-duration-in-seconds: 6
    lease-renewal-interval-in-seconds: 3