server:
  port: 8361

eureka:
  instance:
    hostname: eureka01
  client:
    service-url:
      defaultZone: http://eureka01:8361/eureka,http://eureka02:8362/eureka,http://eureka03:8363/eureka
    register-with-eureka: false
    fetch-registry: false
